config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do 
      post :preview
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    enum country: {
        brasil: "brasil",
        blank: "blank"
    }
    validates :soccer_team, presence: true
    validates :country, presence: true
    validates :name, length: {minimum:4, maximum:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  def preview
    @preview_user = User.new(user_params)
    # redirect_to request.url, notice: "#{@preview_user.valid?} #{@preview_user.errors.full_messages}"
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_url, notice: "Previewed" }
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:name, :email, :password, :soccer_team, :description, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusJSApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, data: { controller: "autosubmit", action: "input->autosubmit#submit"}) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="preview"></div>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
  </div>

  <div data-controller="showhide" data-showhide-show-if-value="brasil">
    <%= form.label :country %><br>
    <%= form.select :country, User.countries, {include_blank: false}, { data: {showhide_target: "input", action: "change->showhide#toggle"}} %><br>

    <div data-showhide-target="output">
      <%= form.label :soccer_team, style: "display: block" %>
      <%= form.text_field :soccer_team %><br>
    </div>
  </div>
      <br>
      <%= form.button "Preview", formaction: preview_users_path, name: "_method", value: "post", data: { autosubmit_target: "submitbutton"}, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
      <%= form.submit "Criar usuário", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
    </div>
<% end %>

app/views/users/_user.html.erb
<div id="users">
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-white border-b">
            <tr> <h2> Lista de Usuários </h2> </tr>
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                #
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                Nome
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                País
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                Time do coração
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                <%= link_to "New user", new_user_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
              </th>
            </tr>
          </thead>
          <% @users.each do |u|%>
            <tbody>
              <tr class="bg-gray-100 border-b">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  <%= u.name %>
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  <%= u.country %>
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  <%= u.soccer_team %>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/_users_form.html.erb
<table class="table-auto">
  <thead>
    <tr>
      <th>Nome</th>
      <th>País</th>
      <th>Time de futebol</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>The Sliding Mr. Bones (Next Stop, Pottersville)</td>
      <td>Malcolm Lockyer</td>
      <td>1961</td>
    </tr>
    <tr>
      <td>Witchy Woman</td>
      <td>The Eagles</td>
      <td>1972</td>
    </tr>
    <tr>
      <td>Shining Star</td>
      <td>Earth, Wind, and Fire</td>
      <td>1975</td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<%
=begin%>
 <div data-controller="checkbox-select-all">
  <input type="checkbox" id="all" name="horns" value="all" data-checkbox-select-all-target="parent", data-action="change->checkbox-select-all#toggleChildren">
  <label for="horns">Todos</label><br>
  <input type="checkbox" id="horns" name="horns" data-checkbox-select-all-target="child" data-action="change->checkbox-select-all#toggleParent">
  <label for="horns">Primeiro</label><br>
  <input type="checkbox" id="horns" name="horns" data-checkbox-select-all-target="child" data-action="change->checkbox-select-all#toggleParent">
  <label for="horns">Segundo</label><br>
  <input type="checkbox" id="horns" name="horns" data-checkbox-select-all-target="child" data-action="change->checkbox-select-all#toggleParent">
  <label for="horns">Terceiro/label><br>
</div> 
<%
=end%>


<p style="color: green"><%= notice %></p>

<%= render "user" %>

app/views/users/new.html.erb
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
</div>

app/views/users/preview.turbo_stream.erb
<%= turbo_stream.update :preview do %>
    <% @preview_user.valid? %>
    Errors
    <%=  @preview_user.errors.full_messages %>
<% end %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>